# Generated by Django 5.1.7 on 2025-04-24 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=400)),
                ('idade', models.IntegerField()),
                ('biografia', models.CharField(max_length=1000)),
                ('interesses', models.CharField(max_length=1000)),
                ('estado_civil', models.CharField(max_length=500)),
                ('foto_perfil', models.ImageField(upload_to='redesocial/fotos')),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('numero_seguidores', models.IntegerField(default=0)),
                ('numero_seguindo', models.IntegerField(default=0)),
                ('dono_da_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('seguidores', models.ManyToManyField(related_name='MeSeguindo', to='redesocial.conta')),
                ('seguindo', models.ManyToManyField(related_name='ContasSeguidas', to='redesocial.conta')),
            ],
        ),
    ]
