# Generated by Django 5.1.7 on 2025-04-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=6000, null=True)),
                ('imagem_postagem', models.ImageField(blank=True, null=True, upload_to='redesocial/ImagemPostagem')),
                ('video', models.FileField(blank=True, null=True, upload_to='redesocial/videos')),
                ('curtidas', models.IntegerField(default=0)),
                ('nao_curtidas', models.IntegerField(default=0)),
                ('quantidade_comentarios', models.IntegerField(default=0)),
                ('dono_postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redesocial.conta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_comentario', models.CharField(max_length=6000)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redesocial.conta')),
                ('postagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redesocial.post')),
            ],
        ),
    ]
