# Generated by Django 5.1.7 on 2025-04-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0002_post_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conta',
            name='idade',
        ),
    ]
