# Generated by Django 5.1.7 on 2025-04-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0003_remove_conta_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='biografia',
            field=models.CharField(default='Não há biografia', max_length=1000),
        ),
        migrations.AlterField(
            model_name='conta',
            name='estado_civil',
            field=models.CharField(default='Não há estado civil', max_length=500),
        ),
        migrations.AlterField(
            model_name='conta',
            name='interesses',
            field=models.CharField(default='Não há interesses', max_length=1000),
        ),
    ]
