# Generated by Django 5.1.7 on 2025-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0004_alter_conta_biografia_alter_conta_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='seguidores',
            field=models.ManyToManyField(blank=True, null=True, related_name='MeSeguindo', to='redesocial.conta'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='seguindo',
            field=models.ManyToManyField(blank=True, null=True, related_name='ContasSeguidas', to='redesocial.conta'),
        ),
    ]
