# Generated by Django 5.1.7 on 2025-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0005_alter_conta_seguidores_alter_conta_seguindo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='seguidores',
            field=models.ManyToManyField(blank=True, related_name='MeSeguindo', to='redesocial.conta'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='seguindo',
            field=models.ManyToManyField(blank=True, related_name='ContasSeguidas', to='redesocial.conta'),
        ),
    ]
