# Generated by Django 5.1.7 on 2025-04-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0007_alter_conta_estado_civil_alter_conta_seguidores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='estado_civil',
            field=models.CharField(blank=True, default='Não há estado civil', max_length=500, null=True),
        ),
    ]
