# Generated by Django 5.1.7 on 2025-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0008_alter_conta_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='biografia',
            field=models.CharField(blank=True, default='Não há biografia', max_length=1000),
        ),
        migrations.AlterField(
            model_name='conta',
            name='estado_civil',
            field=models.CharField(blank=True, default='Não há estado civil', max_length=500),
        ),
        migrations.AlterField(
            model_name='conta',
            name='foto_perfil',
            field=models.ImageField(blank=True, upload_to='redesocial/fotos'),
        ),
        migrations.AlterField(
            model_name='conta',
            name='interesses',
            field=models.CharField(blank=True, default='Não há interesses', max_length=1000),
        ),
    ]
