# Generated by Django 5.1.7 on 2025-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redesocial', '0009_alter_conta_biografia_alter_conta_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='biografia',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='conta',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='conta',
            name='interesses',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
